---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

params:
  FOUNDATION_NAME:

inputs:
  - name: overview-broker
  - name: state

run:
  path: bash
  args:
  - -c
  - |
    set -eu

    pushd state/ci/infrastructure/${FOUNDATION_NAME}
      if [[ "${FOUNDATION_NAME}" == "lola" ]]; then
        eval "$(bbl5 print-env | grep -v '^ssh')"
        export JUMPBOX_IP=$(bosh int vars/jumpbox-vars-file.yml --path /external_ip)
        export CREDHUB_PROXY="ssh+socks5://jumpbox@${JUMPBOX_IP}:22?private-key=$JUMPBOX_PRIVATE_KEY"
        credhub1 login --username=credhub-cli --password="$CREDHUB_PASSWORD" --server="$CREDHUB_SERVER"

        export CF_PASSWORD=$(credhub1 get -n /bosh-${FOUNDATION_NAME}/cf/cf_admin_password | bosh interpolate --path /value -)
      else
        eval "$(bbl print-env)"
        credhub login

        export CF_PASSWORD=$(credhub get -n /bosh-${FOUNDATION_NAME}/cf/cf_admin_password | bosh interpolate --path /value -)
      fi
    popd

    export CF_API=https://api.${FOUNDATION_NAME}.cli.fun

    wget https://s3-us-west-1.amazonaws.com/cf-cli-releases/releases/v6.42.0/cf-cli_6.42.0_linux_x86-64.tgz
    tar zxf cf-cli_6.42.0_linux_x86-64.tgz -C /usr/local/bin
    chmod 755 /usr/local/bin/cf

    cf api $CF_API --skip-ssl-validation
    cf auth admin $CF_PASSWORD

    cf create-org broker
    cf create-space broker -o broker
    cf target -o broker -s broker

    pushd overview-broker
      wget https://raw.githubusercontent.com/mattmcneeney/overview-broker/master/examples/cloudfoundry/manifest.yaml
      sed -i '/random-route/d' manifest.yaml
      cf push
    popd

    set +e # Prevent script from failing if grep exits 1 (no matches found)
    cf service-brokers | grep overview-broker
    found=$?
    set -e

    if [[ $found -eq 1 ]]; then # No broker named overview-broker exists, so let's create it
      cf create-service-broker overview-broker admin password https://overview-broker.${FOUNDATION_NAME}.cli.fun
    elif [[ $found -eq 0 ]]; then # overview-broker already exists, so let's update it
      cf update-service-broker overview-broker admin password https://overview-broker.${FOUNDATION_NAME}.cli.fun
    else
      echo "Failed checking for 'overview-broker'." && exit 1
    fi
