---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

outputs:
- name: vars_path

params:
  CLIENT_SECRET:
  CUSTOM_CLIENT_SECRET:

run:
  path: sh
  args:
  - -c
  - |
    set -eux

    cat << EOF > vars_path/vars.yml
    client-secret: $CLIENT_SECRET
    custom-client-secret: $CUSTOM_CLIENT_SECRET
    EOF
