---
platform: darwin

inputs:
- name: cli
  path: gopath/src/code.cloudfoundry.org/cli

run:
  path: bash
  args:
  - -c
  - |
    set -e

    export GOPATH=$PWD/gopath
    export PATH=$GOPATH/bin:$PATH

    cd $GOPATH/src/code.cloudfoundry.org/cli

    export LC_ALL="en_US.UTF-8"

    go version

    go get -u github.com/onsi/ginkgo/ginkgo
    ginkgo version

    echo -e "\n Checking that packages have been go formatted..."
    gofmt -l . | grep -v -e  ^vendor
    # if we match anything, we have unformatted files
    if [[ $? -eq 0 ]]; then
      echo "Found unlinted files, please run 'make format' and push again."
      exit 1
    fi

    make units-full
