---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-package

params:
  CERT_LOCATION:
  CERT_PASSWORD_LOCATION:
  TARGET_V7:

inputs:
- name: certificates
- name: cli
- name: winstallers

outputs:
- name: signed-windows-zips

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    if [ "$TARGET_V7" == "true" ]; then
      VERSION=$(cat cli/BUILD_VERSION_V7)
      VERSION_SUFFIX="7"
    else
      VERSION=$(cat cli/BUILD_VERSION)
      VERSION_SUFFIX=""
    fi

    awk 'sub("$", "\r")' cli/ci/license/NOTICE > NOTICE
    awk 'sub("$", "\r")' cli/ci/license/LICENSE-WITH-3RD-PARTY-LICENSES > LICENSE

    unzip winstallers/cf${VERSION_SUFFIX}-cli-installer_winx64.zip

    mkdir signed-64
    osslsigncode sign \
      -pkcs12 certificates/$CERT_LOCATION \
      -pass $(cat certificates/$CERT_PASSWORD_LOCATION) \
      -t http://timestamp.comodoca.com/authenticode \
      -h sha256 \
      -in cf${VERSION_SUFFIX}_installer.exe \
      -out signed-64/cf${VERSION_SUFFIX}_installer.exe
    rm -f cf${VERSION_SUFFIX}_installer.exe

    zip -j signed-windows-zips/cf${VERSION_SUFFIX}-cli-installer_${VERSION}_winx64.zip LICENSE NOTICE signed-64/cf${VERSION_SUFFIX}_installer.exe

    unzip winstallers/cf${VERSION_SUFFIX}-cli-installer_win32.zip

    mkdir signed-32
    osslsigncode sign \
      -pkcs12 certificates/$CERT_LOCATION \
      -pass $(cat certificates/$CERT_PASSWORD_LOCATION) \
      -t http://timestamp.comodoca.com/authenticode \
      -h sha256 \
      -in cf${VERSION_SUFFIX}_installer.exe \
      -out signed-32/cf${VERSION_SUFFIX}_installer.exe

    zip -j signed-windows-zips/cf${VERSION_SUFFIX}-cli-installer_${VERSION}_win32.zip LICENSE NOTICE signed-32/cf${VERSION_SUFFIX}_installer.exe
