---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-package

params:
  CERT_LOCATION:
  CERT_PASSWORD_LOCATION:

inputs:
- name: edge-windows-binary-32
- name: edge-windows-binary-64
- name: certificates

outputs:
- name: extracted-binaries

params:
  TARGET_V7:

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    if [ "$TARGET_V7" == "true" ]; then
      SUFFIX="7"
    else
      SUFFIX=""
    fi

    unzip -o edge-windows-binary-64/cf${SUFFIX}-cli_edge_winx64.zip

    osslsigncode sign \
      -pkcs12 certificates/$CERT_LOCATION \
      -pass $(cat certificates/$CERT_PASSWORD_LOCATION) \
      -t http://timestamp.comodoca.com/authenticode \
      -h sha256 \
      -in cf${SUFFIX}.exe \
      -out extracted-binaries/cf-cli_winx64.exe
    rm -f cf${SUFFIX}.exe

    unzip -o edge-windows-binary-32/cf${SUFFIX}-cli_edge_win32.zip

    osslsigncode sign \
      -pkcs12 certificates/$CERT_LOCATION \
      -pass $(cat certificates/$CERT_PASSWORD_LOCATION) \
      -t http://timestamp.comodoca.com/authenticode \
      -h sha256 \
      -in cf${SUFFIX}.exe \
      -out extracted-binaries/cf-cli_win32.exe
